### ISSUE TITLE
Provide means to internally call mintWithPermission

### ISSUE THREAD

**Issue by rahulrumalla** [rugpullindex/ERC4973#21]
As an implementor of ERC4973, I find it flexible to have a means to call `mintWithPermission` from the inherited contract. For example, I want to perform a series of user authorization actions before allowing my contract to `mintWithPermission`.

This is currently possible with `_mint` as it is marked as `internal virtiual`.

I'm unsure what's the right design for this is yet.

**Comment by TimDaub** [comment]
is this and #24 a duplicate?

**Comment by rahulrumalla** [comment]
> please name an example how what you'd like to do internally before calling mintWithPermission. The problem is that mintWithPermission must always be callable according to its interface definition, so e.g. proxying with upfront user authorization would mean being non-compliant with ERC4973

I was trying to go for something like this, but it is not possible due to the current design. 

```solidity
contract AccountBoundToken is ERC4973Permit {
  constructor() ERC4973Permit("Name", "Symbol", "Version") {}

  function getHash(
    address from,
    address to,
    string calldata tokenURI
  ) public view returns (bytes32) {
    return _getHash(from, to, tokenURI);
  }

  function mint(
    address from,
    string calldata tokenURI,
    uint8 v,
    bytes32 r,
    bytes32 s
  ) public returns (uint256) {
    // permform contract specific validation
    bytes memory signature = abi.encodePacked(r, s, v);
    return mintWithPermission(from, tokenURI, signature);
  }
}
```

Th `_mint()` for `ERC4973` is actually also not part of the interface and exposed as `internal virtual`. So I wonder if it would make sense to expose `mintWithPermit` via an interface even. Wdyt?

**Comment by rahulrumalla** [comment]
Another concern here is that *anyone* would be able to call `mintWithPermission` in `MyABT`. There are actually 2 issues here
- I cannot apply any authorizations around the minting
- I cannot also apply any authorization around voucher creations. This is particularly problematic because vouchers can be created off-chain. So a bad/unauthorized actor may issue vouchers for your ABT collection. 

If there's another way to go about this, please let me know.

**Comment by TimDaub** [comment]
> * I cannot apply any authorizations around the `mintWithPermission`

You could apply authorizations. E.g. the `transferFrom(address from, address to, uint256 tokenId)` interface of EIP-721 and EIP-20 also suggests (when viewed in isolation) that "anyone could call it anytime to steal my tokens" but the fact of the matter is that users just have to comply with the interface. And most EIP-721 tokens e.g. only allow the token to be transferred if `from` priorly gave their approval.

So similarly, just because EIP-4973's reference implementation encodes a certain behavior may not mean that e.g. at Otterspace you have to copy it.

Here's e.g. how authorization could happen. The validation of `SignatureChecker` in `mintWithPermission` calls through `from` if it happens to be a contract. You can see it in this mock: https://github.com/rugpullindex/ERC4973/blob/5e7d50ec62d9592f425c4cccd2fc3c3b8aca48c1/src/ERC4973Permit.t.sol#L30

I think so far, it'd be entirely valid to hence restrict `mintWithPermission` such that e.g. `from=address(OtterspaceRegistry)` and where a `to` and `tokenURI` first have to be approved by `OtterspaceRegistry` before they can be minted. I think a variation of the above would fix your problem in a nice way.
