### ISSUE TITLE
consider renaming `mintWithPermission` to `mintFrom`

### ISSUE THREAD

**Issue by TimDaub** [rugpullindex/ERC4973#26]
- in erc20 and erc721: transfer(to, id) and transferFrom(from, to, id)
- so logically: mint(to, url) and mintFrom(from, url, signature)
- althought not quite because mintWithPermission can only be called with to=msg.sender. Is that too opinionated?
- E.g. should anyone be able to call mintWithPermission?

**Comment by markcutajar** [comment]
I think mintWithPermission is better. Relating transferFrom to mintWithPermission i feel it is a bit of a stretch and renaming it to mintFrom would create the illusion that you're minting _from_ something when it's actually minting _with_ approval via the signature. 

I would say that technically it should be unopinionated and everyone is allowed to call the function. The signature would be the only controlling factor (at least at standard level). As long as you have a signature, and that signature is invalidated after use, (through saving of the url or otherwise) it should be fine.

**Comment by TimDaub** [comment]
https://github.com/rugpullindex/ERC4973/commit/27a62d1d61e4890542d941a7be7b314ab8e242d3 has details: There is now a "give" and a "take" method - both consensual.
